### PR TITLE
vm: log instruction

### PR DESCRIPTION
**Pull request by decentralisedkev**

### CODE REVIEW

**Comment by oleganza** [comment]
I've resolved the conflict - one missing piece is this method for `impl Data`:

```rust
    pub fn to_bytes(&self) -> Vec<u8> {
        match self {
            Data::Opaque(data) => data,
            Data::Witness(_) => unimplemented!(),
        }
    }
```

**Comment by decentralisedkev** [comment]
I removed the reference to self, because the item is not put back on the stack, so it is moved.

**Comment by decentralisedkev** [comment]
I think we might get an error, if we try to match on the Vec, but give it a reference

**Comment by decentralisedkev** [comment]
```
Pops data from the stack.
Adds data entry with it to the transaction log.
```

Or should we put the data back on the stack after logging it?

**Comment by oleganza** [comment]
>Or should we put the data back on the stack after logging it?

Nope, the data is popped and moved to the txlog. If the tx needs to reuse that data, it will explicitly `dup` it.

**Comment by oleganza** [comment]
`cargo fmt` is a necessary evil :-/

Otherwise, looks good!

**Pull request merged**
